### ISSUE TITLE
Support for NestJS 9

### ISSUE THREAD

**Issue by nolawnchairs** [BeerMoneyDev/nest-aws-sdk#15]
Peer dependencies for NestJS are locked to specific versions:

```
"peerDependencies": {
    "@nestjs/common": "^7.0.0 || ^8.0.0",
    "@nestjs/core": "^7.0.0 || ^8.0.0",
    ...
}
```
It's safe to assume that the mechanics required for your library to function will not change enough between versions, so it could be better to do this:

```
"peerDependencies": {
    "@nestjs/common": ">= 7.0.0",
    "@nestjs/core": ">= 7.0.0",
    ...
}
```

**Comment by Mateozmaldonado17** [comment]
I have the same problem :/

**Comment by KerryRitter** [comment]
Merged

**Comment by nkusibojoski** [comment]
@KerryRitter can you please also update the  "rimraf": "^3.0.2" version? Currently, the rimraf version is "4.1.1" and it is causing dependency issues when trying to run npm i.
