### ISSUE TITLE
How to load AWS credential from container

### ISSUE THREAD

**Issue by JardarTemalogic** [BeerMoneyDev/nest-aws-sdk#19]
I am using nestjs inside and AWS container, run by Fargate. I want to have the AWS credentials set from how the IAM Role is assigne to the task, as according to this article:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

How would I do this?

**Comment by KerryRitter** [comment]
Sorry, I'm not totally sure what your setup is. If the IAM role is setup on the aws context correctly, it will use it (i.e. lambda) - not sure if that's the same for fargate. We're a thin wrapper to the sdk so it should be fine
