### ISSUE TITLE
AWS SDK v3

### ISSUE THREAD

**Issue by pedromdev** [BeerMoneyDev/nest-aws-sdk#4]
Hi,

This is the best module that integrates AWS SDK and NestJS for me. Recently I found a new version of AWS SDK and it's a monorepo now.

As documented [here](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html), the major differences are split services in small repos and .promise() method is removed.

How complex is to migrate from v2 to v3?

**Comment by pedromdev** [comment]
AWS SDK V3 reference [link](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html)

**Comment by jarcodallo** [comment]
> Hi,
> 
> This is the best module that integrates AWS SDK and NestJS for me. Recently I found a new version of AWS SDK and it's a monorepo now.
> 
> As documented [here](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html), the major differences are split services in small repos and .promise() method is removed.
> 
> How complex is to migrate from v2 to v3?

I think it will be very hard to integrate aws sdk v3 here, because the v3 uses commands for Init, get the progress and get a result. The best option will be create a new `nest-aws-sdk-v3`. What do you think @benMain ?

**Comment by jarcodallo** [comment]
Hi guys @pedromdev @KerryRitter, any news about this? I'm serious thinking in doing a `nestjs-aws-sdk-v3` module, but I don't want to build a new whole module if we can add it here.

**Comment by KerryRitter** [comment]
@jarcodallo  What do you have in mind as far as design? I am also tentative to use this project to support v3 given how many users are using the aws-sdk v2.

**Comment by thomaschaaf** [comment]
@KerryRitter couldn't you just make a new major version?

**Comment by Distortedlogic** [comment]
bump

**Comment by jrista** [comment]
Any progress on updating this for aws sdk v3?

**Comment by ma1022** [comment]
👀👀👀

**Comment by raphaelsoul** [comment]
v3 wanted😘

**Comment by gjuoun** [comment]
Hey, I wrote a library for aws sdk v3 for nest
https://github.com/deligenius/aws-sdk-v3-nest
